#!/usr/bin/env python
# coding: utf-8

from pythonosc import dispatcher

from pythonosc import osc_server 

import time

def eeg_handler(unused_addr, args, ch1, ch2, ch3, ch4,ch5):

    print(ch1)


ip = "127.0.0.1"

port = 6082


dispatcher = dispatcher.Dispatcher()

dispatcher.map("/muse/eeg", eeg_handler, "EEG")

server = osc_server.ThreadingOSCUDPServer(
    (ip, port), dispatcher)

print("Serving on {}".format(server.server_address))